Module globalVariables


    Public userSession As String
    Public userName As String
    Public UsergroupName As String
    Public UserEmailAddress As String
    Public UserMobileNo As String
    Public applicationPath As String
    Public selectingCamaraForm As String

    '//Changes made on 15/07/2025
    '//Changes made by Gagan Tillekeratne
    '//Fixing of Receipt Master Not showing outstanding balance receipts 
    '/Public KBridgeVersion As String = " 4.1.1 "

    '//Changes made on 16/07/2025 
    '//Changes made by Gagan Tillekeratne
    '//Fixing of Monthly Revenue report 
    Public KBridgeVersion As String = " 4.1.2 "

    'Public KBridgeVersion As String = " 4.1.1 "
    '//Receipt Function Fixed
    '//Internal request Date fixed
    '//Beleeta no integration
    '//Program changed by Gagan Tillekeratne - date 09-07-2025.
    Public companyName As String = "Gestetner of Ceylon PLC"
    Public CompanyAddress As String = "248 Vauxhall Street Colombo-02"
    Public ReportgenaratedBy As String = "Report generated by K-Bridge v" & KBridgeVersion & ""
    Public copyrights As String = "K-Bridge Creative Outsource" & KBridgeVersion & "" & Today.Year & ""
    Public selectedCompanyID As String = ""
    Public CodeHeader As String
    Public descriptionHeader As String
    Public openGroupForms As New List(Of String)

    '//Variable required for Camera application
    Public CamaraFormName As String

    '//Variable required for database connection
    Public selectedServerName As String
    Public selectedDatabaseName As String

    '// variables required for crystal report
    Public crystalReportpath As String
    Public reportObj As New Object
    '// variable required for get office time
    Public StartingTime As String
    Public EndingTime As String

    Public vals As List(Of String)

    Public GlobelConnectionStates As String
    Public OpenThroughMDI As Boolean = False
    '// variables for marking attendance  for not checked out
    Public EMPID As String

    '// All Message box messages
    Public SaveMessage As String = "Do you want to save this record:"
    Public EditMessage As String = "Do you want to edit the record:"
    Public DeleteMessage As String = "Are you sure you want to delete this record: "
    Public CreateNewMessgae As String = "Do you wish to reset?"
    Public GenaralErrorMessage As String = "Error occurred while reading the information."
    Public AllradyaddedErrorMessage As String = "This User has already been added by another user, Do you wish to change?"
    Public UserPermissionErrorMessage As String = "You do not have privileges to perform this action."
    Public PermissionReadingErrorMessgae As String = "Error occurred while reading the user permissions. Please re-try"
    Public ExitformMessage As String = "Are you sure you want to exit from "
    Public SAVEError As String = "Error occurred while saving the information."
    Public UserAuthorize As Boolean = False
    Public AuthorizationType As String
    Public AuthorizingFormTag As String

    Public ManuallyOpenForm As Boolean
    Public LPOApproval As Boolean
    Public ManuallyOpenTSDSispatchOrReceved As Boolean
    Public TSDINV_ManagerAppReq As Boolean
    Public TSDInvoiceExpaired As Boolean = False
    '// load general setting variables
    Public Commitment As Integer
    Public GPmerging As Integer
    Public SaleGPMargineVal As Integer
    Public Interest_on_Capitale As Double
    Public CPP_on_Cons_Spears_and_Labor As Double
    Public CPP_ON_BLACK As Double
    Public CPP_ON_COLOR As Double
    Public CPP_ON_BLACK_BLACK_MACHINE As Double
    Public ReplaceRefCode As String = "" '// this variable is use to transfer the replace ref code form purchase order to the Workshop/Marketing Attection

    Public N_Black_Copier_Cost As Double = 0.0
    Public N_Color_Copier_Cost As Double = 0.0
    Public N_Color_Copier_Black As Double = 0.0
    Public N_Duplo_Copier_Cost As Double = 0.0
    Public N_Duplo_ink_cost As Double = 0.0



    Public VAT As Double
    Public VATService As Double
    Public SVAT As Double
    Public NBT1 As Double
    Public NBT2 As Double
    Public SMSstate As Boolean
    Public DeliveryConfirmQueueFormOpen As Boolean = False
    Public P2PCollectionQFormOPen As Boolean = False
    Public DeliveryFormOpenFrom As String
    Public SalesOrderFormOpenBy As String
    Public SalesOrderOpenByReturn As Boolean = False
    Public AutomaticSwUpdateBool As Boolean
    Public VAT_Service_Active As Boolean
    Public MDISizeH As Integer

    Public MDISizeW As Integer
    Public LastMDISizeH As Integer

    Public LastMDISizeW As Integer
    Public GlobleSaleType As String = ""
    Public PO_Path As String = ""
    Public AG_Path As String = ""
    Public INV_Path As String = ""
    Public SaleType As String = ""

    Public LPO_ATT_PATH As String = ""
    Public LocalPurchaseCostUpdated As Boolean = False

    '// DefualtEmail Settings
    Public POP3ServerName As String = "mail.noip.com"
    Public POP3PortNo As Integer = 110
    Public SMTPServerName As String = "smtp.gmail.com"
    Public SMTPPortNo As Integer = 587
    Public GlobleEmailAdd As String = "kbridge@gestetnersl.com"
    Public GlobleEmailPwd As String = "098@321"
    Public BackupServerIPAddress As String

    '// Nashua Lanka Actual job create form function will enable when opening form finance (ex- Open_Actual_N = true )
    Public Open_Actual_N As Boolean = False
    '// Credit note Variables
    Public ReturnDemoRefCode As String = ""

    Public ReplacePNList As New List(Of String)
    Public ExchangeRate_Buy As Double = 0.0

    '// P2P Return base sales order return serial number calculation disable picking SN
    Public Return_SN As String = ""

    Public Open_P2P_By_Creditnote As Boolean = False


    '// API Path
    Public ApiPath As String = "kbridgesl.com"
    '// debtors checking day limit
    Public DebtorsCheckDayLimit As Integer = 0

    '// Machine ref code Pno/Dno
    Public MachineRefCode As String = ""

    '// Default printers Names
    Public DefaultPrinterName As String = ""


End Module
